/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.github.nowelium.titanium.module.thumbnail;

import java.io.ByteArrayOutputStream;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.graphics.Bitmap;
import android.graphics.Bitmap.CompressFormat;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.webkit.MimeTypeMap;

@Kroll.module(name="Thumbnail", id="com.github.nowelium.titanium.module.thumbnail")
public class ThumbnailModule extends KrollModule
{
  
  // Standard Debugging variables
  private static final String LCAT = "ThumbnailModule";
  private static final boolean DBG = TiConfig.LOGD;

  // You can define constants with @Kroll.constant, for example:
  // @Kroll.constant public static final String EXTERNAL_NAME = value;
  
  @Kroll.constant
  public static final String MIME_JPEG = "image/jpeg";
  
  @Kroll.constant
  public static final String MIME_PNG = "image/png";
  
  public ThumbnailModule(TiContext tiContext) {
    super(tiContext);
  }

  // Methods
  @Kroll.method
  public TiBlob resize(TiBlob blob){
    return resizeFromBlob(blob, 320, 480, true, MIME_JPEG);
  }
  
  @Kroll.method
  public TiBlob resizeTo(TiBlob blob, KrollDict args){
    final int width = args.optInt("width", 320).intValue();
    final int height = args.optInt("height", 480).intValue();
    final boolean keepAspect = args.optBoolean("keepAspect", true);
    final String mimeType = args.optString("mimeType", MIME_JPEG);
    
    return resizeFromBlob(blob, width, height, keepAspect, mimeType);
  }
  
  private TiBlob compress(Bitmap bitmap, CompressFormat format, String mimeType){
    final ByteArrayOutputStream out = new ByteArrayOutputStream();
    if(bitmap.compress(format, 80, out)){
      return TiBlob.blobFromData(context, out.toByteArray(), mimeType);
    }
    // defaults: PNG(TiBlob.java:76<compress>)
    return TiBlob.blobFromImage(context, bitmap);
  }
  
  private TiBlob compress(Bitmap bitmap, String mimeType){
    if(MIME_PNG.equals(mimeType)){
      return compress(bitmap, CompressFormat.PNG, MIME_PNG);
    }
    return compress(bitmap, CompressFormat.JPEG, MIME_JPEG);
  }
  
  private TiBlob resizeFromBlob(TiBlob blob, int width, int height, boolean keepAspect, String mimeType){
    final byte[] binary = blob.getBytes();
    final Bitmap target = BitmapFactory.decodeByteArray(binary, 0, binary.length);
    final Bitmap resized = resizeToSize(target, width, height, keepAspect);
    try {
      return compress(resized, mimeType);
    } finally {
      target.recycle();
      resized.recycle();
    }
  }

  private Bitmap resizeToSize(Bitmap bitmap, int targetWidth, int targetHeight, boolean preserveAspectRatio){
    final int originalWidth = bitmap.getWidth();
    final int originalHeight = bitmap.getHeight();
    final float imageWidth = 0.0f + originalWidth;
    final float imageHeight = 0.0f + originalHeight;
    if(imageWidth < 1.0f){
      return Bitmap.createBitmap(bitmap, 0, 0, 0, 0);
    }
    if(imageHeight < 1.0f){
      return Bitmap.createBitmap(bitmap, 0, 0, 0, 0);
    }
    
    final float aspectRatio = imageHeight / imageHeight;
    final float targetAspectRatio = targetWidth / targetHeight;
    final Matrix projectTo = new Matrix();
    if (preserveAspectRatio) {
      if (targetAspectRatio < aspectRatio) {
        float width = targetWidth;
        float height = width / aspectRatio;
        projectTo.postScale(width / imageWidth, height / imageHeight);
      } else {
        float height = targetHeight;
        float width = height * aspectRatio;
        projectTo.postScale(width / imageWidth, height / imageHeight);
      }
    } else {
      // Don't preserve the aspect ratio.
      projectTo.postScale(targetWidth / imageWidth, targetHeight / imageHeight);
    }    
    return Bitmap.createBitmap(bitmap, 0, 0, originalWidth, originalHeight, projectTo, true);
  }
  
}
